adopted-ember-addons/ember-notify

README.md, addon/components/ember-notify.js, addon/message.js, app/templates/components/ember-notify.hbs
This allow us to change the default time out that will close the message. So, I don't need to specify everywhere the `closeAfter`. If the `closeAfter` is present in the message, it will use that value instead of the default.
=> Allow change the default value for closeAfter in the template

addon/components/ember-notify.js
I ran into a problem when testing an application using `ember-notify` whereby `show` was getting called on a destroyed component. Since it seems there's no reason to ever queue messages if the component has been destroyed, I've added a conditional statement checking `isDestroyed`.
=> only show a notification if the component hasn't been destroyed

app/templates/components/ember-notify.hbs
DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper is deprecated. Please use the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.
=> fix deprecation in ember canary

README.md, addon/components/ember-notify.js, tests/unit/ember-notify-test.js
Hey @aexmachina I'd like to add support for thoughtbot's [refills](http://refills.bourbon.io/components) flash stylings. Here's what the error message looks like:
Would you be willing to accept this PR? Thanks!
=> adds support for thoughtbot's refills flashes

package.json
related to https://github.com/aexmachina/ember-notify/issues/54#issuecomment-129957857
=> Moved object-assign to correct dependencies hash as dependencies was listed twice

addon/initializer.js
Starting with Ember 2.1 providing two arguments to an initializer
will trigger a deprecation.
Read more : http://emberjs.com/deprecations/v2.x/#toc_initializer-arity
=> Clear deprecation warning for initializer :snowboarder:

addon/index.js, tests/unit/components/ember-notify-test.js
* Previously, `text` would get confused with `options` if notify was sent text marked as safe by ember (e.g. from an ember-i18n translation)
* If `text` is a subclass of `SafeString`, call `toString` to render the safestring to a string, then resume
* Added a test as well
* Refs #62
=> Add support for Ember.Handlebars.SafeString

README.md, addon/components/ember-notify.js, examples/custom-position-animations.css, tests/unit/components/ember-notify-test.js, vendor/ember-notify.css
This will allow users to disable any of the supplied animations by instantiating the component like so: 
```
{{ember-notify classPrefix=“custom-namespace”}}
```
I will polish this documentation for inclusion in the README once the PR is finalized.
=> #68 allow namespace CSS class

addon/components/ember-notify/message.js, tests/unit/components/ember-notify-test.js
Without checking if the component is being destroyed, the `this.$()`
will return null and set will later be called on a destroyed message
object.
=> #69 validate state before proxying close action

README.md, addon/templates/components/ember-notify.hbs, addon/templates/components/ember-notify/message.hbs, tests/integration/components/ember-notify-test.js, tests/integration/components/ember-notify/message-test.js
This PR adds the support of using arbitrary markup in messages (in case you wanna use a dedicated icon for close etc):
```handlebars
{{#ember-notify messageStyle='bootstrap' class="notification" as |message close|}}
{{! what about using a button for closing the message ? }}
<input class="close" type="button" value="close" {{action close}}>
<span class='message'>{{message.text}}</span>
{{/ember-notify}}
```
=> custom message markup

addon/index.js, tests/helpers/start-app.js
In ember >= v2.5.0 `ember-notify` throw a deprecation:
> Usage of `Ember.merge` is deprecated, use `Ember.assign` instead.
It's occurs because Ember.merge will be removed in ember#3.0.0: [link to blog](http://emberjs.com/deprecations/v2.x/#toc_ember-merge).
I add `assign` variable, which equals to Ember.assign (for ember >= 2.1.0) or Ember.merge (for oldest ember versions).
=> Fix Ember.merge deprecation: use Ember.assign if it is available

addon/index.js, tests/unit/components/ember-notify-test.js
Resolves the deprecation notification for `Ember.Handlebars.SafeString` issue as described in aexmachina/ember-notify#92
You can learn more about it here http://emberjs.com/blog/2016/09/08/ember-2-8-and-2-9-beta-released.html#toc_code-ember-string-ishtmlsafe-code
=> Replace Ember.Handlebars.SafeString to Ember.String.htmlSafe

addon/index.js
Use `Ember.String.isHTMLSafe()` to do the SafeString check as discussed here https://github.com/emberjs/ember.js/issues/13318
=> Fixed the SafeString check

addon/index.js, package.json
Latest release places the polyfill in the “native” location, instead of needing to import the function.
Note: This is part of an effort to get all users of the polyfill updated.. workmanw/ember-string-ishtmlsafe-polyfill#5
=> Update isHTMLSafe polyfill dep

README.md, package.json
Transferring to `adopted-ember-addons`.
Closes #129.
@aexmachina there are a few steps to be completed on your side:
https://github.com/adopted-ember-addons/program-guidelines
Thanks!
=> Update repository for the addon to be transferred

README.md
I dug this up from https://github.com/aexmachina/ember-notify/issues/29
It's a feature worth documenting. As a new user I was looking for this specifically, because I've been given a prototype with css but no logic, and it looks like this tackles the hard parts (like turning off for tests).
=> doc turning off css import in ember-cli-build

README.md
Updates the readme for Ember Octane. In detail it does:
- Refactor curly bracket component invocation to angle bracket syntax.
- It remove duplicated examples (curly + angle bracket). It's not necessary anymore in my opinion as there isn't anything special about conversion for this addon. It does neither use positional params in curly invocation nor require special arguments for the mapping to HTML attributes.
- Use `{{on}}` element modifier for event binding instead of `{{action}}`.
- Uses native classes in the example.
- Use `@action` decorator instead of `actions` hash in the examples.
=> update readme for Ember Octane

CHANGELOG.md, README.md, addon/components/ember-notify/message.js, addon/message.js, tests/unit/components/ember-notify-test.js
Using the `visible` property was broken (#138). Therefore I added a new method to bring back the functionality.
=>  Add `close` method for manually closing message

addon/index.js
Update ember/string with ember/template import of isHTMLsafe
It is related to this deprecation https://deprecations.emberjs.com/v3.x#toc_ember-string-htmlsafe-ishtmlsafe
The thing is, my app is using Ember 3.27 and I had an error from above using notify addon. I changed import and used my fork version from GH since then, all good. I assume it maybe false change, because it should work fine until Ember 4.0.
Meanwhile we can wait for 4.0 release and merge it after. 
The  `@ember/template` import is available since 3.8 release https://api.emberjs.com/ember/3.8/modules/@ember%2Ftemplate
=> Fix TypeError: _string.isHTMLSafe is not a function

addon/components/ember-notify.js
In Ember 3.27+, accessing `oneWay` off of `computed` will throw a deprecation warning, which turns into a hard error in Ember 4.x (currently `ember-beta`). Instead, we can fix it to directly import `oneWay` from the `@ember/object/computed` module
=> Fix deprecation in Ember 3.27+, import error in Ember 4.x

addon/components/ember-notify/message.js
This should fix the following deprecation warning:
```
DEPRECATION: Using `run.later` has been deprecated. Instead, import the value directly from @ember/runloop:
import { later } from '@ember/runloop';  [deprecation id: deprecated-run-loop-and-computed-dot-access]
```
Fixes https://github.com/adopted-ember-addons/ember-notify/issues/181 
This fix is required to use this addon on Ember 4.
=> Fix `run.later` deprecation warning

addon/index.js
Fixes the Ember.assign deprecation: https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign
This was finally dropped from Ember canary and is breaking tests in consuming projects that test against the canary scenario.
=> Replace Ember assign with Object.assign
